import {
    Location,
    Document,
    Menu as IconMenu,
    Setting,
    Briefcase,
    Tools,
    Timer
} from '@element-plus/icons'
import {
    ElConfigProvider,
    ElContainer,
    ElAside,
    ElHeader,
    ElMain,
    ElMenu,
    ElSubMenu,
    ElMenuItemGroup,
    ElMenuItem,
    ElButton,
    ElIcon,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElTabs,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTag,
    ElSelect,
    ElOption,
    ElPagination,
    ElInput,
    ElForm,
    ElFormItem,
    ElDatePicker

} from 'element-plus'

const Comp = {
    Location,
    Document,
    IconMenu,
    Briefcase,
    Setting,
    Tools,
    Timer,

    ElConfigProvider,
    ElContainer,
    ElAside,
    ElHeader,
    ElMain,
    ElMenu,
    ElSubMenu,
    ElMenuItemGroup,
    ElMenuItem,
    ElButton,
    ElIcon,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElTabs,
    ElTabPane,
    ElTable,
    ElTableColumn,
    ElTag,
    ElSelect,
    ElOption,
    ElPagination,
    ElInput,
    ElForm,
    ElFormItem,
    ElDatePicker
}
export default Comp;